// components/Projects.vue
<script setup>
const projects = [
  {
    name: " EzzyGabby Photography",
    description:
      "  A minimalist and modern portfolio site built to showcase creative work in a clean, distraction-free layout. Designed to reflect the photographer's visual style and provide a seamless browsing experience ",
    link: {
      live: "https://ezzygabby.vercel.app",
      github: "https://github.com/JohnSanusi/EzzyGabby",
    },
    techs: [
      {
        name: "Nuxt.js",
        icon: "/icons/nuxt.svg",
      },
      {
        name: "Tailwind CSS",
        icon: "/icons/tailwindcss.svg",
      },
      {
        name: "Vercel",
        icon: "/icons/vercel.svg",
      },
    ],
  },

  {
    name: "GHIT",
    description:
      "A responsive and branded website for a modern tech school, focused on clear structure and intuitive navigation. Built to communicate the school's mission and offerings with a polished user experience",
    link: {
      live: "https://ghit.vercel.app",
      github: "https://github.com/JohnSanusi/GHIT",
    },
    techs: [
      {
        name: "Nuxt.js",
        icon: "/icons/nuxt.svg",
      },
      {
        name: "Tailwind CSS",
        icon: "/icons/tailwindcss.svg",
      },
      {
        name: "Node.js",
        icon: "/icons/nodejs.svg",
      },
      {
        name: "Express.js",
        icon: "/icons/express.svg",
      },
      {
        name: "MongoDB",
        icon: "/icons/mongodb.svg",
      },
      {
        name: "Vercel",
        icon: "/icons/vercel.svg",
      },
      {
        name: "Render",
        icon: "/icons/render.svg",
      },
    ],
  },
  {
    name: " GHIT-Admin",
    description:
      "A custom-built admin interfae for managing student data, courses, amd registerations, Designed with simplicity and clarity in mind to support day-to-day administrative tasks efficiently",
    link: {
      live: "#",
      github: "https://github.com/JohnSanusi/GHIT-ADMIN",
    },
    techs: [
      {
        name: "Nuxt.js",
        icon: "/icons/nuxt.svg",
      },
      {
        name: "Tailwind CSS",
        icon: "/icons/tailwindcss.svg",
      },

      {
        name: "Node.js",
        icon: "/icons/nodejs.svg",
      },
      {
        name: "Express.js",
        icon: "/icons/express.svg",
      },
      {
        name: "MongoDB",
        icon: "/icons/mongodb.svg",
      },
      {
        name: "Vercel",
        icon: "/icons/vercel.svg",
      },
      {
        name: "Render",
        icon: "/icons/render.svg",
      },
    ],
  },
];
</script>
<template>
  <section id="projects" class="mt-10 p-6 flex flex-col">
    <div class="relative" data-aos="fade-down" data-aos-duration="1000">
      <h2 class="text-3xl font-bold tracking-normal mb-7">Recent Works</h2>
      <div class="absolute top-9 left-0 h-[6px] w-25 bg-blue-500"></div>
      <div class="absolute top-11 left-0 h-[6px] w-18 bg-blue-500"></div>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 p-2">
      <div v-for="(project, index) in projects" :key="index">
        <div
          class="bg-gray-900 rounded-xl p-6 shadow-md flex flex-col gap-4 w-full max-w-sm h-auto md:h-80"
          data-aos="fade-in"
          data-aos-duration="1000"
        >
          <!-- Title -->
          <h3 class="text-xl font-bold">{{ project.name }}</h3>

          <!-- Description -->
          <p class="text-sm">
            {{ project.description }}
          </p>

          <!-- Tech Stack Icons -->
          <div
            class="flex flex-wrap justify-between items-center gap-2 mt-2 max-w-full"
          >
            <div
              v-for="(tech, index) in project.techs"
              :key="index"
              class="flex flex-col items-center"
              data-aos="fade-in"
              data-aos-duration="1000"
            >
              <img
                :src="tech.icon"
                class="w-6 h-6 filter invert brightness-125"
              />
              <span class="mt-1 text-sm">{{ tech.name }}</span>
            </div>
          </div>

          <!-- Buttons -->
          <div class="flex gap-4 mt-auto">
            <a
              :href="project.link.live"
              target="_blank"
              class="bg-blue-500 px-4 py-2 text-sm rounded hover:bg-blue-600 transition"
            >
              Live Site
            </a>
            <a
              :href="project.link.github"
              target="_blank"
              class="bg-gray-700 px-4 py-2 text-sm rounded hover:bg-gray-600 transition"
            >
              GitHub
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

// components/Projects.tsx
'use client';

import { motion } from 'framer-motion';
import { Github, ExternalLink, ArrowUpRight } from 'lucide-react';
import { useState } from 'react';

const projects = [
    {
        title: 'EzzyGabby PhotoGraphy',
        description: "A minimalist and modern portfolio site built to showcase creative work in a clean, distraction-free layout. Designed to reflect the photographer's visual style and provide a seamless browsing experience",
        tags: ['Nuxt.js', 'Tailwind', 'TypeScript'],
        github: 'https://github.com/JohnSanusi/EZZYGABBY',
        demo: 'https://ezzygabby.vercel.app',
        image: '/ezzy.png',
    },
    {
        title: 'Ex2325 Fashion Store',
        description: 'Another amazing project showcasing full-stack capabilities and attention to detail in design and user experience.',
        tags: ['Next.js', 'Tailwind', 'Node.js', 'Express', 'TypeScript'],
        github: 'https://github.com/JohnSanusi/EX2325-Shoe-Store',
        demo: 'https://ex2325.vercel.app',
        image: '/ex2325.png',
    },
    {
        title: 'Lumea Collections',
        description: 'A sleek and modern e-commerce website built for a startup and small brand to sell products online with ease. Designed with a minimalist layout and smooth navigation to deliver a seamless shopping experience for customers',
        tags: ['Next.js', 'Tailwind', 'Node.js', 'Express', 'TypeScript'],
        github: 'https://github.com/JohnSanusi/LUMEA',
        demo: 'https://lumeax.vercel.app',
        image: '/lume.png',
    },
];

export default function Projects() {
    return (
        <section id="projects" className="py-32 px-6 bg-[#000000] relative overflow-hidden">
            {/* Background Decoration */}
            <motion.div
                animate={{
                    scale: [1, 1.1, 1],
                    opacity: [0.02, 0.04, 0.02],
                }}
                transition={{ duration: 8, repeat: Infinity, ease: "easeInOut" }}
                className="absolute top-20 right-0 w-[500px] h-[500px] bg-[#1d1d1f] rounded-full blur-[120px]"
            />

            <div className="max-w-6xl mx-auto relative z-10">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
                    className="mb-16"
                >
                    <h2 className="text-4xl md:text-5xl font-bold text-[#f5f5f7] mb-4 tracking-tight">
                        Selected Projects
                    </h2>
                    <motion.div
                        className="h-1 bg-[#f5f5f7] rounded-full"
                        initial={{ width: 0 }}
                        whileInView={{ width: '100px' }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.8, delay: 0.2 }}
                    />
                </motion.div>

                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
                    {projects.map((project, index) => (
                        <ProjectCard key={index} project={project} index={index} />
                    ))}
                </div>
            </div>
        </section>
    );
}

function ProjectCard({ project, index }: { project: typeof projects[0]; index: number }) {
    const [isHovered, setIsHovered] = useState(false);

    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: index * 0.1, ease: [0.16, 1, 0.3, 1] }}
            onHoverStart={() => setIsHovered(true)}
            onHoverEnd={() => setIsHovered(false)}
            className="group relative bg-[#1c1c1e] rounded-3xl p-8 shadow-lg border border-[#38383a] overflow-hidden transition-all duration-300 hover:border-[#48484a]"
        >
            {/* Subtle Hover Background */}
            <motion.div
                className="absolute inset-0 bg-[#2c2c2e]"
                initial={{ opacity: 0 }}
                animate={{ opacity: isHovered ? 1 : 0 }}
                transition={{ duration: 0.3 }}
            />

            <div className="relative z-10">
                {/* Project Image */}
                <motion.div
                    className="relative w-full h-48 mb-6 rounded-2xl overflow-hidden bg-[#2c2c2e]"
                    animate={isHovered ? { scale: 1.02 } : { scale: 1 }}
                    transition={{ duration: 0.3 }}
                >
                    <img
                        src={project.image}
                        alt={project.title}
                        className="w-full h-full object-cover"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-[#1c1c1e] via-transparent to-transparent opacity-60" />
                </motion.div>

                <motion.h3
                    className="text-2xl font-semibold text-[#f5f5f7] mb-4"
                    animate={isHovered ? { x: 3 } : { x: 0 }}
                    transition={{ duration: 0.2 }}
                >
                    {project.title}
                </motion.h3>

                <p className="text-[#86868b] mb-8 leading-relaxed text-lg">
                    {project.description}
                </p>

                <div className="flex flex-wrap gap-2 mb-8">
                    {project.tags.map((tag, i) => (
                        <motion.span
                            key={i}
                            whileHover={{ scale: 1.05 }}
                            className="text-xs font-medium text-[#f5f5f7] bg-[#38383a] px-3 py-1 rounded-full cursor-default transition-all hover:bg-[#48484a]"
                        >
                            {tag}
                        </motion.span>
                    ))}
                </div>

                <div className="flex items-center gap-6">
                    <motion.a
                        href={project.github}
                        target="_blank"
                        rel="noopener noreferrer"
                        whileHover={{ x: 3 }}
                        className="flex items-center text-sm font-medium text-[#86868b] hover:text-[#f5f5f7] transition-colors group/link"
                    >
                        <Github className="w-5 h-5 mr-2" />
                        Code
                        <ArrowUpRight className="w-4 h-4 ml-1 opacity-0 group-hover/link:opacity-100 transition-opacity" />
                    </motion.a>
                    <motion.a
                        href={project.demo}
                        target="_blank"
                        rel="noopener noreferrer"
                        whileHover={{ x: 3 }}
                        className="flex items-center text-sm font-medium text-[#86868b] hover:text-[#f5f5f7] transition-colors group/link"
                    >
                        <ExternalLink className="w-5 h-5 mr-2" />
                        Live Demo
                        <ArrowUpRight className="w-4 h-4 ml-1 opacity-0 group-hover/link:opacity-100 transition-opacity" />
                    </motion.a>
                </div>
            </div>
        </motion.div>
    );
}
